# Generated by Django 6.0.3 on 2026-03-19 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mcmethod', '0003_rename_title_mcmethod_name_alter_mcmethod_alias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mcbuilder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='название мультивременного композита', max_length=50, verbose_name='Название')),
                ('mcfile', models.CharField(help_text='англоязычное имя выходного файла', max_length=20, verbose_name='Имя файла')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='дата создания выходного файла', verbose_name='Дата создания')),
                ('description', models.TextField(blank=True, help_text='описание результата', null=True, verbose_name='Описание')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mcmethod', to='mcmethod.mcmethod', verbose_name='Методы МВК')),
            ],
            options={
                'verbose_name': 'Сервис создания МВК',
                'verbose_name_plural': 'Сервис создания МВК',
            },
        ),
    ]
