# Generated by Django 6.0.3 on 2026-03-19 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcbuilder', '0001_initial'),
        ('mcmethod', '0003_rename_title_mcmethod_name_alter_mcmethod_alias'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mcbuilder',
            options={'verbose_name': 'cервис создания МВК', 'verbose_name_plural': 'cервис создания МВК'},
        ),
        migrations.AlterField(
            model_name='mcbuilder',
            name='method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mcmethod.mcmethod', verbose_name='Методы МВК'),
        ),
    ]
