# Generated by Django 6.0.3 on 2026-03-19 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcbuilder', '0002_alter_mcbuilder_options_alter_mcbuilder_method'),
        ('mcmethod', '0003_rename_title_mcmethod_name_alter_mcmethod_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcbuilder',
            name='method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Mcmethod_name', to='mcmethod.mcmethod', verbose_name='Методы МВК'),
        ),
    ]
