# Generated by Django 6.0.3 on 2026-03-19 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcbuilder', '0003_alter_mcbuilder_method'),
        ('mcmethod', '0004_alter_mcmethod_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcbuilder',
            name='method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mcmethod_name', to='mcmethod.mcmethod', verbose_name='Методы МВК'),
        ),
    ]
