# Generated by Django 6.0.3 on 2026-03-19 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcbuilder', '0004_alter_mcbuilder_method'),
        ('mcmethod', '0004_alter_mcmethod_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcbuilder',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='mcbuilder',
            name='method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mcmethod.mcmethod', verbose_name='Методы МВК'),
        ),
    ]
