# Generated by Django 6.0.3 on 2026-04-17 07:25

import django.db.models.deletion
import filer.fields.folder
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0018_alter_file_options'),
        ('mcbuilder', '0005_mcbuilder_file_alter_mcbuilder_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcbuilder',
            name='files_folder',
            field=filer.fields.folder.FilerFolderField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filer.folder', verbose_name='Папка с исходниками'),
        ),
        migrations.AlterField(
            model_name='mcbuilder',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/%Y%m%d/', verbose_name='Имя файла'),
        ),
    ]
