# Generated by Django 6.0.3 on 2026-04-17 07:37

import django.db.models.deletion
import filer.fields.folder
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0018_alter_file_options'),
        ('mcbuilder', '0006_mcbuilder_files_folder_alter_mcbuilder_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mcbuilder',
            name='file',
        ),
        migrations.AlterField(
            model_name='mcbuilder',
            name='files_folder',
            field=filer.fields.folder.FilerFolderField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='filer.folder', verbose_name='Папка с исходниками'),
        ),
    ]
