# Generated by Django 6.0.3 on 2026-04-20 08:03

import django.db.models.deletion
import filer.fields.folder
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0018_alter_file_options'),
        ('mcbuilder', '0007_remove_mcbuilder_file_alter_mcbuilder_files_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcbuilder',
            name='files_folder',
            field=filer.fields.folder.FilerFolderField(blank=True, help_text='название папки', null=True, on_delete=django.db.models.deletion.SET_NULL, to='filer.folder', verbose_name='Папка с исходниками'),
        ),
    ]
