# Generated by Django 6.0.3 on 2026-04-20 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcbuilder', '0008_alter_mcbuilder_files_folder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mcbuilder',
            options={'verbose_name': 'параметры создания МВК', 'verbose_name_plural': 'параметры создания МВК'},
        ),
        migrations.AddField(
            model_name='mcbuilder',
            name='builded',
            field=models.BooleanField(default=True, help_text='композит успешно создан', verbose_name='Выполнено'),
        ),
        migrations.AlterField(
            model_name='mcbuilder',
            name='mcfile',
            field=models.CharField(help_text='англоязычное имя выходного файла', max_length=20, verbose_name='Имя композита'),
        ),
    ]
