# Generated by Django 6.0.3 on 2026-04-20 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcbuilder', '0009_alter_mcbuilder_options_mcbuilder_builded_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcbuilder',
            name='builded',
            field=models.BooleanField(default=False, help_text='композит успешно создан', verbose_name='Выполнено'),
        ),
    ]
