# Generated by Django 5.2.12 on 2026-04-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcbuilder', '0010_alter_mcbuilder_builded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcbuilder',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mcbuilder',
            name='mcfile',
            field=models.CharField(blank=True, help_text='англоязычное имя выходного файла', max_length=255, null=True, verbose_name='Имя композита'),
        ),
    ]
