# Generated by Django 5.2.12 on 2026-04-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcbuilder', '0011_alter_mcbuilder_id_alter_mcbuilder_mcfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcbuilder',
            name='mcfile',
            field=models.URLField(blank=True, help_text='cсылка на результат', max_length=255, null=True, verbose_name='Скачать'),
        ),
    ]
