# Generated by Django 5.2.12 on 2026-04-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcbuilder', '0012_alter_mcbuilder_mcfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcbuilder',
            name='mcfile',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='cсылка'),
        ),
    ]
