# Generated by Django 5.2.12 on 2026-04-26 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcbuilder', '0013_alter_mcbuilder_mcfile'),
        ('mcmethod', '0005_alter_mcmethod_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcbuilder',
            name='resampl',
            field=models.BooleanField(default=False, help_text='привести снимки к единой проекции, размерам, разрешению и extent.', verbose_name='Ресемплинг'),
        ),
        migrations.AlterField(
            model_name='mcbuilder',
            name='mcfile',
            field=models.CharField(blank=True, help_text='путь к файлу результата', max_length=255, null=True, verbose_name='Имя файла результата'),
        ),
        migrations.AlterField(
            model_name='mcbuilder',
            name='method',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, to='mcmethod.mcmethod', verbose_name='Методы МВК'),
        ),
    ]
