# Generated by Django 5.2.12 on 2026-05-14 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcbuilder', '0014_mcbuilder_resampl_alter_mcbuilder_mcfile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcbuilder',
            name='agregat',
            field=models.CharField(choices=[('median', 'Медиана'), ('mean', 'Среднее'), ('max', 'Максимум'), ('min', 'Минимум')], default='median', max_length=10, verbose_name='Метод агрегации'),
        ),
        migrations.AlterField(
            model_name='mcbuilder',
            name='resampl',
            field=models.BooleanField(default=False, help_text='привести снимки к единой проекции, размерам, разрешению и extent.', verbose_name='Выполнить ресемплинг'),
        ),
    ]
