# Generated by Django 5.2.12 on 2026-05-18 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcbuilder', '0015_mcbuilder_agregat_alter_mcbuilder_resampl'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mcbuilder',
            name='author',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mcbuilder',
            name='agregat',
            field=models.CharField(choices=[('median', 'Медиана'), ('mean', 'Среднее'), ('max', 'Максимум'), ('min', 'Минимум')], default='median', help_text='для многовременного композита', max_length=10, verbose_name='Метод агрегации'),
        ),
    ]
