# Generated by Django 5.2.12 on 2026-05-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcbuilder', '0018_alter_mcbuilder_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcbuilder',
            name='ctypes',
            field=models.CharField(choices=[('range', 'Размах по временному ряду'), ('std', 'Стандартное отклонение'), ('coefficient_of_variation', 'Коэффициент вариации'), ('difference_sum', 'Cумма абсолютных разностей')], default='range', help_text='с поддержкой многоканальных файлов', max_length=30, verbose_name='Тип композита'),
        ),
    ]
