# Generated by Django 5.2.12 on 2026-05-31 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcbuilder', '0019_mcbuilder_ctypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcbuilder',
            name='bands',
            field=models.CharField(choices=[('1', 'Синий канал'), ('2', 'Зеленый канал'), ('3', 'Красный канал'), ('All', 'Все каналы')], default='2', help_text='каналы снимка для создания композита', max_length=30, verbose_name='Рабочий канал'),
        ),
    ]
