# Generated by Django 5.2.12 on 2026-05-31 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcbuilder', '0023_alter_mcbuilder_bands'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcbuilder',
            name='bands',
            field=models.CharField(choices=[('Red', 'Красный канал'), ('Green', 'Зеленый канал'), ('Blue', 'Синий канал'), ('RGB', 'Все каналы')], default='2', help_text='исходные каналы для создания композита', max_length=30, verbose_name='Рабочий канал'),
        ),
    ]
