# Generated by Django 5.2.12 on 2026-06-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcbuilder', '0025_alter_mcbuilder_bands'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcbuilder',
            name='bands',
            field=models.CharField(choices=[('red', 'Красный канал'), ('green', 'Зеленый канал'), ('blue', 'Синий канал'), ('rgb', 'Все каналы RGB')], default='Red', help_text='исходные каналы для создания композита', max_length=30, verbose_name='Рабочий канал'),
        ),
    ]
