# Generated by Django 5.2.12 on 2026-06-03 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcbuilder', '0026_alter_mcbuilder_bands'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcbuilder',
            name='mcfile',
            field=models.CharField(blank=True, help_text='путь к файлу результата', max_length=610, null=True, verbose_name='Имя файла результата'),
        ),
    ]
