# Generated by Django 5.2.12 on 2026-07-01 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcbuilder', '0027_alter_mcbuilder_mcfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcbuilder',
            name='geotron',
            field=models.BooleanField(default=False, help_text='Опубликовать результат на ГИП "Геотрон"?', verbose_name='Опубликован'),
        ),
    ]
