# Generated by Django 5.2.12 on 2026-07-01 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcbuilder', '0028_mcbuilder_geotron'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcbuilder',
            name='geotron',
            field=models.BooleanField(default=False, help_text='Опубликовать результат на ГИП "Геотрон"?', verbose_name='ГИП "Геотрон"'),
        ),
    ]
