# Generated by Django 5.2.12 on 2026-07-01 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcbuilder', '0029_alter_mcbuilder_geotron'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcbuilder',
            name='geotron',
            field=models.BooleanField(default=False, help_text='публикация результата на ГИП "Геотрон"', verbose_name='ГИП "Геотрон"'),
        ),
        migrations.AlterField(
            model_name='mcbuilder',
            name='resampl',
            field=models.BooleanField(default=False, help_text='привести снимки к единой проекции, размерам, разрешению и extent', verbose_name='Выполнить ресемплинг'),
        ),
    ]
