# Generated by Django 5.2.12 on 2026-07-03 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcbuilder', '0030_alter_mcbuilder_geotron_alter_mcbuilder_resampl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcbuilder',
            name='builded',
            field=models.BooleanField(default=False, verbose_name='Выполнено'),
        ),
        migrations.AlterField(
            model_name='mcbuilder',
            name='ctypes',
            field=models.CharField(choices=[('range', 'Размах по временному ряду'), ('std', 'Стандартное отклонение'), ('coefficient_of_variation', 'Коэффициент вариации'), ('sum', 'Cумма абсолютных разностей')], default='range', help_text='с поддержкой многоканальных файлов', max_length=30, verbose_name='Тип композита'),
        ),
        migrations.AlterField(
            model_name='mcbuilder',
            name='mcfile',
            field=models.CharField(blank=True, max_length=610, null=True, verbose_name='Имя файла результата'),
        ),
    ]
