# Generated by Django 5.2.12 on 2026-07-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcbuilder', '0031_alter_mcbuilder_builded_alter_mcbuilder_ctypes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcbuilder',
            name='ctypes',
            field=models.CharField(choices=[('range', 'Размах по временному ряду'), ('std', 'Стандартное отклонение'), ('cov', 'Коэффициент вариации'), ('sum', 'Cумма абсолютных разностей')], default='range', help_text='с поддержкой многоканальных файлов', max_length=30, verbose_name='Тип композита'),
        ),
    ]
