# Generated by Django 5.2.12 on 2026-07-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcbuilder', '0032_alter_mcbuilder_ctypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcbuilder',
            name='autolevels',
            field=models.CharField(choices=[(None, 'Без обработки'), ('percentile', 'Растяжка по процентилям'), ('adaptive', 'Автоматический выбор'), ('minmax', 'Полный диапазон'), ('std', 'Стандартное отклонение')], default='none', help_text='улучшающая обработка результата методом растяжки гистограммы', max_length=30, verbose_name='Автоуровни'),
        ),
    ]
