# Generated by Django 5.2.12 on 2026-07-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcbuilder', '0034_alter_mcbuilder_autolevels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcbuilder',
            name='autolevels',
            field=models.CharField(blank=True, choices=[(None, 'Без обработки'), ('adaptive', 'Автоматический выбор'), ('percentile', 'Растяжка по процентилям'), ('minmax', 'Полный диапазон'), ('std', 'Стандартное отклонение')], default=None, help_text='улучшающая обработка методами растяжки гистограммы', max_length=30, null=True, verbose_name='Метод автоконтраста'),
        ),
    ]
