# Generated by Django 5.2.12 on 2026-07-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcbuilder', '0035_alter_mcbuilder_autolevels'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcbuilder',
            name='metthresh',
            field=models.CharField(choices=[('max', 'Максимальная разность по каналам'), ('mean', 'Средняя абсолютная разность'), ('euclidean', 'Евклидово расстояние в пространстве каналов'), ('sum', 'Сумма абсолютных разностей (SAD)')], default='max', help_text='Пороговое обнаружение изменений для многоканальных данных', max_length=50, verbose_name='Метод вычисления разности'),
        ),
        migrations.AddField(
            model_name='mcbuilder',
            name='threshold',
            field=models.PositiveIntegerField(blank=True, default=None, help_text='если не задано, то порог расчитывается автоматически', null=True, verbose_name='Пороговое значение'),
        ),
    ]
