# Generated by Django 5.2.12 on 2026-07-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcbuilder', '0036_mcbuilder_metthresh_mcbuilder_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcbuilder',
            name='threshold',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='если равно 0, то порог расчитывается автоматически', verbose_name='Пороговое значение'),
        ),
    ]
