[supervisord]
nodaemon=true

[program:gunicorn]
command=/opt/conda/envs/multicomp/bin/gunicorn --bind 0.0.0.0:8000 --workers 3 --timeout 3600 --keep-alive 5 --max-requests 1000 --max-requests-jitter 50 config.wsgi:application
directory=/app
autostart=true
autorestart=true
stderr_logfile=/var/log/gunicorn.err.log
stdout_logfile=/var/log/gunicorn.out.log

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true
stderr_logfile=/var/log/nginx.err.log
stdout_logfile=/var/log/nginx.out.log