# Generated by Django 6.0.3 on 2026-03-19 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mcmethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('alias', models.CharField(max_length=20, verbose_name='Псевдоним')),
                ('description', models.CharField(max_length=150, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Метод создания МВК',
                'verbose_name_plural': 'Методы создания МВК',
            },
        ),
    ]
