# Generated by Django 6.0.3 on 2026-03-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcmethod', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcmethod',
            name='description',
            field=models.TextField(blank=True, help_text='описание метода', null=True, verbose_name='Описание'),
        ),
    ]
