# Generated by Django 6.0.3 on 2026-03-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcmethod', '0002_alter_mcmethod_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mcmethod',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='mcmethod',
            name='alias',
            field=models.CharField(help_text='англоязычный псевдоним метода', max_length=20, verbose_name='Псевдоним'),
        ),
    ]
