# Generated by Django 6.0.3 on 2026-03-19 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcmethod', '0003_rename_title_mcmethod_name_alter_mcmethod_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcmethod',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название'),
        ),
    ]
