# Generated by Django 5.2.12 on 2026-04-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcmethod', '0004_alter_mcmethod_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcmethod',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
